In [1]:
import pandas as pd

In [2]:
# ->Filteration
# data={"name":,"age":,"city":}
# 1.show people from delhi
# 2.show people with age b/w 25 and 30
# 3.sort data by age desc    sort_value
# 4.find youngest person df.loc[df["age"].idxmin()]
# 5.find oldest person
# from tips dataset
# filter rows by smoker=no and total_bill>=10
data={"name":["shalini","nidhi","raman","atul"],
     "age":[23,45,78,12],
     "city":["delhi","chd","chd","delhi"]
     }
df=pd.DataFrame(data)
df

      name  age   city
0  shalini   23  delhi
1    nidhi   45    chd
2    raman   78    chd
3     atul   12  delhi

In [3]:
df[df["city"]=="delhi"]

      name  age   city
0  shalini   23  delhi
3     atul   12  delhi

In [5]:
df[(df["age"]>20) & (df["age"]<30)]

      name  age   city
0  shalini   23  delhi

In [7]:
df.sort_values(by="age",ascending=False)

      name  age   city
2    raman   78    chd
1    nidhi   45    chd
0  shalini   23  delhi
3     atul   12  delhi

In [13]:
df.loc[[df["age"].idxmax()]]

    name  age city
2  raman   78  chd

In [14]:
pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in c:\programdata\anaconda3\lib\site-packages (0.12.2)
Requirement already satisfied: pandas>=0.25 in c:\programdata\anaconda3\lib\site-packages (from seaborn) (1.5.3)
Requirement already satisfied: numpy!=1.24.0,>=1.17 in c:\users\admin\appdata\roaming\python\python310\site-packages (from seaborn) (1.24.4)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in c:\programdata\anaconda3\lib\site-packages (from seaborn) (3.7.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.4)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.8.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.0.9)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (9.4.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.25.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.0.5)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\roaming\python\python310\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (24.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.25->seaborn) (2022.7)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [15]:
import seaborn as sns
tips=sns.load_dataset("tips")
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [17]:
dt=tips[(tips["day"]=="Sun") & 
     (tips["time"]=="Dinner") & (tips["sex"]=="Male")]
dt

     total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
7         26.88  3.12  Male     No  Sun  Dinner     4
8         15.04  1.96  Male     No  Sun  Dinner     2
9         14.78  3.23  Male     No  Sun  Dinner     2
10        10.27  1.71  Male     No  Sun  Dinner     2
12        15.42  1.57  Male     No  Sun  Dinner     2
13        18.43  3.00  Male     No  Sun  Dinner     4
15        21.58  3.92  Male     No  Sun  Dinner     2
17        16.29  3.71  Male     No  Sun  Dinner     3
41        17.46  2.54  Male     No  Sun  Dinner     2
42        13.94  3.06  Male     No  Sun  Dinner     2
43         9.68  1.32  Male     No  Sun  Dinner     2
44        30.40  5.60  Male     No  Sun  Dinner     4
45        18.29  3.00  Male     No  Sun  Dinner     2
46        22.23  5.00  Male     No  Sun  Dinner     2
47        32.40  6.00  Male     No  Sun  Dinner     4
48        28.55  2.05  Male     No  Sun  Dinner     3
49        18.04  3.00  Male     No  Sun  Dinner     2
50        12.54  2.50  Male     No  Sun  Dinner     2
53         9.94  1.56  Male     No  Sun  Dinner     2
54        25.56  4.34  Male     No  Sun  Dinner     4
55        19.49  3.51  Male     No  Sun  Dinner     2
112       38.07  4.00  Male     No  Sun  Dinner     3
113       23.95  2.55  Male     No  Sun  Dinner     2
116       29.93  5.07  Male     No  Sun  Dinner     4
150       14.07  2.50  Male     No  Sun  Dinner     2
151       13.13  2.00  Male     No  Sun  Dinner     2
152       17.26  2.74  Male     No  Sun  Dinner     3
153       24.55  2.00  Male     No  Sun  Dinner     4
154       19.77  2.00  Male     No  Sun  Dinner     4
156       48.17  5.00  Male     No  Sun  Dinner     6
159       16.49  2.00  Male     No  Sun  Dinner     4
160       21.50  3.50  Male     No  Sun  Dinner     4
161       12.66  2.50  Male     No  Sun  Dinner     2
163       13.81  2.00  Male     No  Sun  Dinner     2
165       24.52  3.48  Male     No  Sun  Dinner     3
166       20.76  2.24  Male     No  Sun  Dinner     2
167       31.71  4.50  Male     No  Sun  Dinner     4
172        7.25  5.15  Male    Yes  Sun  Dinner     2
173       31.85  3.18  Male    Yes  Sun  Dinner     2
174       16.82  4.00  Male    Yes  Sun  Dinner     2
175       32.90  3.11  Male    Yes  Sun  Dinner     2
176       17.89  2.00  Male    Yes  Sun  Dinner     2
177       14.48  2.00  Male    Yes  Sun  Dinner     2
179       34.63  3.55  Male    Yes  Sun  Dinner     2
180       34.65  3.68  Male    Yes  Sun  Dinner     4
181       23.33  5.65  Male    Yes  Sun  Dinner     2
182       45.35  3.50  Male    Yes  Sun  Dinner     3
183       23.17  6.50  Male    Yes  Sun  Dinner     4
184       40.55  3.00  Male    Yes  Sun  Dinner     2
185       20.69  5.00  Male     No  Sun  Dinner     5
187       30.46  2.00  Male    Yes  Sun  Dinner     5
189       23.10  4.00  Male    Yes  Sun  Dinner     3
190       15.69  1.50  Male    Yes  Sun  Dinner     2

In [26]:
# ->Data Cleaning
# same dataframe with None in age and city
# 1.df.isnull()
# 2.df.dropna()
# 3.fill missing age with avg age
# 4.fill city with unknown
data={"name":["shalini","nidhi","raman","atul"],
     "age":[None,45,78,12],
     "city":["delhi","chd",None,"delhi"]
     }
df=pd.DataFrame(data)
df

      name   age   city
0  shalini   NaN  delhi
1    nidhi  45.0    chd
2    raman  78.0   None
3     atul  12.0  delhi

In [22]:
df.dropna()

    name   age   city
1  nidhi  45.0    chd
3   atul  12.0  delhi

In [28]:
df["age"]=df["age"].fillna(df["age"].mean())
df["city"]=df["city"].fillna("Unknown")
df

      name   age     city
0  shalini  45.0    delhi
1    nidhi  45.0      chd
2    raman  78.0  Unknown
3     atul  12.0    delhi

In [ ]:
# ->Grouping
# data={"desg":,"dept":,"salary":} (split->apply->combine)
# 1.avg salary by dept      df.groupby("dept")["salary"].mean()
# 2.max salary by dept      df.groupby("dept")["salary"].max()
# 3.count employees per dept    df.groupby("dept").size()
# 4.multiple agg   .agg(["mean","max","min"])
# 5.diff agg per col  df.groupby("dept").agg({"salary":["mean","max"],"desg":"count"})
# 6.grouping on multiple cols 
# 7.iterating on group for name,group in df.groupby("dept")
# 8.filtering groups  df.groupby("dept").filter(lambda x:x["salary"].mean()>50000)
# 9.named agg df.groupby("dept").agg(avg_salary=("salary","mean"),max_salary=("salary","max"))
# 10.grouping with cond   df.groupby(df["salary"]>60000)["salary"].mean()
# 11.ranking within group df["rank_in_grp]=df.groupby("dept")["salary"].rank(ascending=False)   
# df[df["rank_in_grp"]<=2]
# 12.which dept has highest avg.salary   df.groupby("dept")["salary"].mean().idxmax()
# gapminder
# 1.groupby year avg lifeExp  .mean()   .agg(np.mean)
# 2.df.groupby(["year","continent"])[["lifeexp","gdppercap"]].agg(np.mean)
# reset_index()
# 3.avg total_bill for each value of smoker,day and time

In [30]:
data={"dept":["it","sales","it","marketing","hr","sales","sales"],
       "salary":[20000,25000,40000,27000,12000,25678,34000],
      "desg":["a","b","b","aa","a","b","aa"]
     }
df=pd.DataFrame(data)
df

        dept  salary desg
0         it   20000    a
1      sales   25000    b
2         it   40000    b
3  marketing   27000   aa
4         hr   12000    a
5      sales   25678    b
6      sales   34000   aa

In [32]:
df.groupby("dept")["salary"].mean()

dept
hr           12000.0
it           30000.0
marketing    27000.0
sales        28226.0
Name: salary, dtype: float64

In [38]:
df.groupby("dept").agg({"salary":[min,max,"mean"]})

          salary
             min    max     mean
dept
hr         12000  12000  12000.0
it         20000  40000  30000.0
marketing  27000  27000  27000.0
sales      25000  34000  28226.0

In [39]:
gap=pd.read_csv("gapminder.tsv",delimiter="\t")
gap.head(10)

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106
5  Afghanistan      Asia  1977   38.438  14880372  786.113360
6  Afghanistan      Asia  1982   39.854  12881816  978.011439
7  Afghanistan      Asia  1987   40.822  13867957  852.395945
8  Afghanistan      Asia  1992   41.674  16317921  649.341395
9  Afghanistan      Asia  1997   41.763  22227415  635.341351

In [41]:
gap.groupby("continent").agg({"lifeExp":"mean","pop":sum})

             lifeExp          pop
continent
Africa     48.865330   6187585961
Americas   64.658737   7351438499
Asia       60.064903  30507333901
Europe     71.903686   6181115304
Oceania    74.326208    212992136

In [43]:
gap.groupby(["continent","country"])["lifeExp"].mean().reset_index()

    continent         country    lifeExp
0      Africa         Algeria  59.030167
1      Africa          Angola  37.883500
2      Africa           Benin  48.779917
3      Africa        Botswana  54.597500
4      Africa    Burkina Faso  44.694000
..        ...             ...        ...
137    Europe     Switzerland  75.565083
138    Europe          Turkey  59.696417
139    Europe  United Kingdom  73.922583
140   Oceania       Australia  74.662917
141   Oceania     New Zealand  73.989500

[142 rows x 3 columns]

In [44]:
gap.groupby("continent").size()

continent
Africa      624
Americas    300
Asia        396
Europe      360
Oceania      24
dtype: int64

In [45]:
# continent------>country  rank based on lifeexp
# best 2 countries from each continent
df["rank"]=

        dept  salary desg
0         it   20000    a
1      sales   25000    b
2         it   40000    b
3  marketing   27000   aa
4         hr   12000    a
5      sales   25678    b
6      sales   34000   aa

In [47]:
df["rank"]=df.groupby("dept")["salary"].rank(ascending=False)
df[df["rank"]<=2]

        dept  salary desg  rank
0         it   20000    a   2.0
2         it   40000    b   1.0
3  marketing   27000   aa   1.0
4         hr   12000    a   1.0
5      sales   25678    b   2.0
6      sales   34000   aa   1.0

In [51]:
gap["rank"]=gap.groupby(["continent","country"])["lifeExp"].rank(ascending=False)
gap[gap["rank"]<=2]

          country continent  year  lifeExp       pop    gdpPercap  rank
10    Afghanistan      Asia  2002   42.129  25268405   726.734055   2.0
11    Afghanistan      Asia  2007   43.828  31889923   974.580338   1.0
22        Albania    Europe  2002   75.651   3508512  4604.211737   2.0
23        Albania    Europe  2007   76.423   3600523  5937.029526   1.0
34        Algeria    Africa  2002   70.994  31287142  5288.040382   2.0
...           ...       ...   ...      ...       ...          ...   ...
1679  Yemen, Rep.      Asia  2007   62.698  22211743  2280.769906   1.0
1685       Zambia    Africa  1977   51.386   5216550  1588.688299   2.0
1686       Zambia    Africa  1982   51.821   6100407  1408.678565   1.0
1699     Zimbabwe    Africa  1987   62.351   9216418   706.157306   1.0
1700     Zimbabwe    Africa  1992   60.377  10704340   693.420786   2.0

[284 rows x 7 columns]

In [53]:
# gap.groupby("continent").filter(lambda x:x["lifeExp"]>70)
# ["lifeExp"].mean()

TypeError: filter function returned a Series, but expected a scalar bool

In [55]:
df.groupby("dept").filter(lambda x:x["salary"].mean()>20000)

        dept  salary desg  rank
0         it   20000    a   2.0
1      sales   25000    b   3.0
2         it   40000    b   1.0
3  marketing   27000   aa   1.0
5      sales   25678    b   2.0
6      sales   34000   aa   1.0

In [56]:
gap.groupby("continent")["lifeExp"].mean()

continent
Africa      48.865330
Americas    64.658737
Asia        60.064903
Europe      71.903686
Oceania     74.326208
Name: lifeExp, dtype: float64

In [57]:
gap.groupby("continent").filter(lambda x:x["lifeExp"].mean()>70)

             country continent  year  lifeExp       pop     gdpPercap  rank
12           Albania    Europe  1952   55.230   1282697   1601.056136  12.0
13           Albania    Europe  1957   59.280   1476505   1942.284244  11.0
14           Albania    Europe  1962   64.820   1728137   2312.888958  10.0
15           Albania    Europe  1967   66.220   1984060   2760.196931   9.0
16           Albania    Europe  1972   67.690   2263554   3313.422188   8.0
...              ...       ...   ...      ...       ...           ...   ...
1603  United Kingdom    Europe  1987   75.007  56981620  21664.787670   5.0
1604  United Kingdom    Europe  1992   76.420  57866349  22705.092540   4.0
1605  United Kingdom    Europe  1997   77.218  58808266  26074.531360   3.0
1606  United Kingdom    Europe  2002   78.471  59912431  29478.999190   2.0
1607  United Kingdom    Europe  2007   79.425  60776238  33203.261280   1.0

[384 rows x 7 columns]

In [ ]:
1.group by country,year    mean pop
2.group by continent,country only records >1990
3.group by continent 2 most popul